version: '3'

services:


# openssl pkcs12 -in keystore.p12 -nokeys -out certificate.crt -nodes
# openssl pkcs12 -in keystore.p12 -nocerts -out private.key -nodes
  nginx:
    image: nginx:latest
    ports:
      - "20130:20130"
    volumes:
      - ./nginx/config.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificate.crt:/etc/nginx/certificate.crt:ro
      - ./nginx/new_private.key:/etc/nginx/private.key:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - logging
    depends_on:
      - mb-api

  mb-api:
    build: .
    container_name: mb-api
    image: michaelkey/mb-api:0.0.1-SNAPSHOT
    ports:
      - "20134:20134"
    volumes:
      - ./logs:/var/log/spring
      - ./files/public:/app/files/public
      - ./files/private:/app/files/private
    environment:
      SERVER_PORT: 20134
      SPRING_PROFILES_ACTIVE: docker
      TZ: Europe/Warsaw
    depends_on:
      - postgres
    networks:
      - logging
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "3309:5432"
    volumes:
      - postgres-data:/data/postgres
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontgotosql
      PGDATA: /data/postgres
      TZ: Europe/Warsaw
    networks:
      - postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      TZ: Europe/Warsaw
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped



  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.48.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - logging
    ports:
      - "9090:9090"
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw


  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"
    networks:
      - logging
    restart: unless-stopped


  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log/spring
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - logging
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - logging
    restart: unless-stopped

volumes:
  logs:
  postgres-data:
  pgadmin-data:
  grafana-data:

networks:
  postgres:
    driver: bridge
  logging:
    driver: bridge