
# Use the official OpenJDK 17 image as the base
FROM openjdk:17-jdk-slim

# Set the working directory to /app
WORKDIR /app

# Create the required directory with appropriate permissions
RUN mkdir -p /app/module-main/files/public && \
    chmod 777 /app/module-main/files/public

RUN mkdir -p /app/module-main/files/private && \
    chmod 777 /app/module-main/files/private


# Variable ARG for the JAR file name; you can adjust this value during the build of the image
ARG JAR_FILE=/motobudzetapi/target/*.jar

# Copy the application JAR file into the image at location /app/app.jar
COPY ${JAR_FILE} app.jar

# Expose port 20134
EXPOSE 20134

# Run the application
ENTRYPOINT ["java","-jar","/app/app.jar"]



# Stage 1: Build the application
#FROM maven:3.8.4-openjdk-17 as builder
#
#WORKDIR /app
#
## Copy the pom.xml and source code
#COPY ./pom.xml ./pom.xml
#COPY ./src ./src
#
## Build the application without running tests
#RUN mvn clean install -DskipTests
#
## Stage 2: Create the final Docker image
#FROM openjdk:17-jdk-slim
#
#WORKDIR /app
#
## Copy the JAR from the build stage
#COPY --from=builder /app/target/*.jar app.jar
#
#EXPOSE 20134
#
#ENTRYPOINT ["java","-jar","/app/app.jar"]
