# Use the official OpenJDK 17 image as the base
FROM openjdk:17-jdk-slim

# Set the working directory to /app
WORKDIR /app

# Create the required directory with appropriate permissions
RUN mkdir -p /app/module-main/files/public && \
    chmod 777 /app/module-main/files/public

RUN mkdir -p /app/module-main/files/private && \
    chmod 777 /app/module-main/files/private


# Variable ARG for the JAR file name; you can adjust this value during the build of the image
ARG JAR_FILE=target/*.jar

# Copy the application JAR file into the image at location /app/app.jar
COPY ${JAR_FILE} app.jar

# Expose port 20134
EXPOSE 20134

# Run the application
ENTRYPOINT ["java","-jar","/app/app.jar"]