global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mb-api'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mb-api:20134']
        labels:
          application: 'mb-api'
    authorization:
      type: Bearer
      credentials: 'Bearer prometheus9090auth'

  - job_name: 'mailing-service'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mailing-service:20135']
        labels:
          application: 'mailing-service'