global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mb-api'
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['motobudzet.pl']
        labels:
          application: 'mb-api'
#          bearer_token_file: '/ścieżka/do/pliku/z/tokenem'
#        headers:
#          prometheus-service: 'prometheus9090auth'
    authorization:
      type: Bearer
      credentials: 'Bearer prometheus9090auth'
#    tls_config:
#      cert_file: /etc/prometheus/motobudzet.pl.intermediate.pem
#      key_file: /etc/prometheus/motobudzet.pl.key
#      insecure_skip_verify: false