server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: 'mb-api'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'mb-api'
          __path__: '/var/log/spring/mb-api.*.log'

  - job_name: 'mailing-service'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'mailing-service'
          __path__: '/var/log/spring/mailing-service.*.log'