server:
  port: 20135

spring:
  application:
    name: mailing-service
  kafka:
    consumer:
      bootstrap-servers: kafka-broker:9092
      group-id: mailing-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: pl.motobudzet.api.model.EmailNotificationRequest
        spring.json.trusted.packages: '*'


  mail:
    host: serwer2379308.home.pl
    port: 587
    username: info@motobudzet.pl
    password: dontgotosql
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
            auth: true
            starttls:
              enable: true
            connection-timeout: 5000
            timeout: 3000
            write timeout: 5000

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    key-values:
      application: mailing-service
  endpoints:
    web:
      exposure:
        #        include: health,info,prometheus
        include: "*"
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

email-service:
  url: https://motobudzet.pl
  email-address: info@motobudzet.pl