server:
  port: 20135

spring:
  application:
    name: mailing-service

  mail:
    host: serwer2379308.home.pl
    port: 587
    username: info@motobudzet.pl
    password: dontgotosql
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
            auth: true
            starttls:
              enable: true
            connection-timeout: 5000
            timeout: 3000
            write timeout: 5000

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    key-values:
      application: mailing-service
  endpoints:
    web:
      exposure:
        #        include: health,info,prometheus
        include: "*"
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
