spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
#    url: jdbc:postgresql://serwer2379308.home.pl/37515270_motobudzet69
#    username: 37515270_motobudzet69
#    password: jamajskiHolender69
#    url:
#    username:
#    password:
    hikari:
      max-lifetime: 600000
    url: jdbc:postgresql://localhost:5432/motobudzet
    username: postgres
    password: dontgotosql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        show_sql: true
        hbm2ddl:
          auto: none
#          auto: create-drop
  banner:
    location: classpath:banner.txt
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 20134

mailing:
    module:
      enabled: false
