-- --------------------------------------------------------
-- Host:                         codego.pl
-- Wersja serwera:               10.0.28-MariaDB-0+deb8u1 - (Debian)
-- Serwer OS:                    debian-linux-gnu
-- HeidiSQL Wersja:              9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Zrzut struktury tabela pogoda.miasta
CREATE TABLE IF NOT EXISTS cities (
    id SERIAL PRIMARY KEY,
    state_id INT NOT NULL DEFAULT 0,
    name VARCHAR(150) NOT NULL DEFAULT '0'
);

-- Zrzucanie danych dla tabeli pogoda.miasta: ~918 rows (około)
/*!40000 ALTER TABLE `miasta` DISABLE KEYS */;
INSERT INTO cities (state_id, name) VALUES
    (1, 'Bolesławiec'),
    (1, 'Nowogrodziec'),
    (1, 'Bielawa'),
    (1, 'Dzierżoniów'),
    (1, 'Pieszyce'),
    (1, 'Piława Górna'),
    (1, 'Niemcza'),
    (1, 'Głogów'),
    (1, 'Góra'),
    (1, 'Wąsosz'),
    (1, 'Jawor'),
    (1, 'Bolków'),
    (1, 'Karpacz'),
    (1, 'Kowary'),
    (1, 'Piechowice'),
    (1, 'Szklarska Poręba'),
    (1, 'Kamienna Góra'),
    (1, 'Lubawka'),
    (1, 'Duszniki-Zdrój'),
    (1, 'Kłodzko'),
    (1, 'Kudowa-Zdrój'),
    (1, 'Nowa Ruda'),
    (1, 'Polanica-Zdrój'),
    (1, 'Bystrzyca Kłodzka'),
    (1, 'Lądek-Zdrój'),
    (1, 'Międzylesie'),
    (1, 'Radków'),
    (1, 'Stronie Śląskie'),
    (1, 'Szczytna'),
    (1, 'Chojnów'),
    (1, 'Prochowice'),
    (1, 'Lubań'),
    (1, 'Świeradów-Zdrój'),
    (1, 'Leśna'),
    (1, 'Olszyna'),
    (1, 'Lubin'),
    (1, 'Ścinawa'),
    (1, 'Gryfów Śląski'),
    (1, 'Lubomierz'),
    (1, 'Lwówek Śląski'),
    (1, 'Mirsk'),
    (1, 'Wleń'),
    (1, 'Milicz'),
    (1, 'Oleśnica'),
    (1, 'Bierutów'),
    (1, 'Międzybórz'),
    (1, 'Syców'),
    (1, 'Twardogóra'),
    (1, 'Oława'),
    (1, 'Jelcz-Laskowice'),
    (1, 'Chocianów'),
    (1, 'Polkowice'),
    (1, 'Przemków'),
    (1, 'Strzelin'),
    (1, 'Wiązów'),
    (1, 'Środa Śląska'),
    (1, 'Świdnica'),
    (1, 'Świebodzice'),
    (1, 'Jaworzyna Śląska'),
    (1, 'Strzegom'),
    (1, 'Żarów'),
    (1, 'Oborniki Śląskie'),
    (1, 'Prusice'),
    (1, 'Trzebnica'),
    (1, 'Żmigród'),
    (1, 'Boguszów-Gorce'),
    (1, 'Jedlina-Zdrój'),
    (1, 'Szczawno-Zdrój'),
    (1, 'Głuszyca'),
    (1, 'Mieroszów'),
    (1, 'Brzeg Dolny'),
    (1, 'Wołów'),
    (1, 'Kąty Wrocławskie'),
    (1, 'Sobótka'),
    (1, 'Siechnice'),
    (1, 'Bardo'),
    (1, 'Ząbkowice Śląskie'),
    (1, 'Ziębice'),
    (1, 'Złoty Stok'),
    (1, 'Zawidów'),
    (1, 'Zgorzelec'),
    (1, 'Bogatynia'),
    (1, 'Pieńsk'),
    (1, 'Węgliniec'),
    (1, 'Wojcieszów'),
    (1, 'Złotoryja'),
    (1, 'Świerzawa'),
    (1, 'Jelenia Góra'),
    (1, 'Legnica'),
    (1, 'Wrocław'),
    (1, 'Wałbrzych'),
    (2, 'Aleksandrów Kujawski'),
    (2, 'Ciechocinek'),
    (2, 'Nieszawa'),
    (2, 'Brodnica'),
    (2, 'Górzno'),
    (2, 'Jabłonowo Pomorskie'),
    (2, 'Koronowo'),
    (2, 'Solec Kujawski'),
    (2, 'Chełmno'),
    (2, 'Golub-Dobrzyń'),
    (2, 'Kowalewo Pomorskie'),
    (2, 'Łasin'),
    (2, 'Radzyń Chełmiński'),
    (2, 'Inowrocław'),
    (2, 'Gniewkowo'),
    (2, 'Janikowo'),
    (2, 'Kruszwica'),
    (2, 'Pakość'),
    (2, 'Lipno'),
    (2, 'Dobrzyń nad Wisłą'),
    (2, 'Skępe'),
    (2, 'Mogilno'),
    (2, 'Strzelno'),
    (2, 'Kcynia'),
    (2, 'Mrocza'),
    (2, 'Nakło nad Notecią'),
    (2, 'Szubin'),
    (2, 'Radziejów'),
    (2, 'Piotrków Kujawski'),
    (2, 'Rypin'),
    (2, 'Kamień Krajeński'),
    (2, 'Sępólno Krajeńskie'),
    (2, 'Więcbork'),
    (2, 'Nowe'),
    (2, 'Świecie'),
    (2, 'Chełmża'),
    (2, 'Tuchola'),
    (2, 'Wąbrzeźno'),
    (2, 'Kowal'),
    (2, 'Brześć Kujawski'),
    (2, 'Chodecz'),
    (2, 'Izbica Kujawska'),
    (2, 'Lubień Kujawski'),
    (2, 'Lubraniec'),
    (2, 'Barcin'),
    (2, 'Janowiec Wielkopolski'),
    (2, 'Łabiszyn'),
    (2, 'Żnin'),
    (2, 'Bydgoszcz'),
    (2, 'Grudziądz'),
    (2, 'Toruń'),
    (2, 'Włocławek'),
    (3, 'Międzyrzec Podlaski'),
    (3, 'Terespol'),
    (3, 'Biłgoraj'),
    (3, 'Frampol'),
    (3, 'Józefów'),
    (3, 'Tarnogród'),
    (3, 'Rejowiec Fabryczny'),
    (3, 'Siedliszcze'),
    (3, 'Hrubieszów'),
    (3, 'Janów Lubelski'),
    (3, 'Modliborzyce'),
    (3, 'Krasnystaw'),
    (3, 'Kraśnik'),
    (3, 'Annopol'),
    (3, 'Urzędów'),
    (3, 'Lubartów'),
    (3, 'Kock'),
    (3, 'Ostrów Lubelski'),
    (3, 'Bełżyce'),
    (3, 'Bychawa'),
    (3, 'Łęczna'),
    (3, 'Łuków'),
    (3, 'Stoczek Łukowski'),
    (3, 'Opole Lubelskie'),
    (3, 'Poniatowa'),
    (3, 'Parczew'),
    (3, 'Puławy'),
    (3, 'Kazimierz Dolny'),
    (3, 'Nałęczów'),
    (3, 'Radzyń Podlaski'),
    (3, 'Dęblin'),
    (3, 'Ryki'),
    (3, 'Świdnik'),
    (3, 'Piaski'),
    (3, 'Tomaszów Lubelski'),
    (3, 'Lubycza Królewska'),
    (3, 'Łaszczów'),
    (3, 'Tyszowce'),
    (3, 'Włodawa'),
    (3, 'Krasnobród'),
    (3, 'Szczebrzeszyn'),
    (3, 'Zwierzyniec'),
    (3, 'Biała Podlaska'),
    (3, 'Chełm'),
    (3, 'Lublin'),
    (3, 'Zamość'),
    (4, 'Kostrzyn nad Odrą'),
    (4, 'Witnica'),
    (4, 'Gubin'),
    (4, 'Krosno Odrzańskie'),
    (4, 'Międzyrzecz'),
    (4, 'Skwierzyna'),
    (4, 'Trzciel'),
    (4, 'Nowa Sól'),
    (4, 'Bytom Odrzański'),
    (4, 'Kożuchów'),
    (4, 'Nowe Miasteczko'),
    (4, 'Cybinka'),
    (4, 'Ośno Lubuskie'),
    (4, 'Rzepin'),
    (4, 'Słubice'),
    (4, 'Dobiegniew'),
    (4, 'Drezdenko'),
    (4, 'Strzelce Krajeńskie'),
    (4, 'Lubniewice'),
    (4, 'Sulęcin'),
    (4, 'Torzym'),
    (4, 'Świebodzin'),
    (4, 'Zbąszynek'),
    (4, 'Babimost'),
    (4, 'Czerwieńsk'),
    (4, 'Kargowa'),
    (4, 'Nowogród Bobrzański'),
    (4, 'Sulechów'),
    (4, 'Gozdnica'),
    (4, 'Żagań'),
    (4, 'Iłowa'),
    (4, 'Małomice'),
    (4, 'Szprotawa'),
    (4, 'Łęknica'),
    (4, 'Żary'),
    (4, 'Jasień'),
    (4, 'Lubsko'),
    (4, 'Sława'),
    (4, 'Szlichtyngowa'),
    (4, 'Wschowa'),
    (4, 'Gorzów Wielkopolski'),
    (4, 'Zielona Góra'),
    (5, 'Bełchatów'),
    (5, 'Zelów'),
    (5, 'Kutno'),
    (5, 'Krośniewice'),
    (5, 'Żychlin'),
    (5, 'Łask'),
    (5, 'Łęczyca'),
    (5, 'Łowicz'),
    (5, 'Koluszki'),
    (5, 'Rzgów'),
    (5, 'Tuszyn'),
    (5, 'Drzewica'),
    (5, 'Opoczno'),
    (5, 'Konstantynów Łódzki'),
    (5, 'Pabianice'),
    (5, 'Działoszyn'),
    (5, 'Pajęczno'),
    (5, 'Sulejów'),
    (5, 'Wolbórz'),
    (5, 'Poddębice'),
    (5, 'Uniejów'),
    (5, 'Radomsko'),
    (5, 'Kamieńsk'),
    (5, 'Przedbórz'),
    (5, 'Rawa Mazowiecka'),
    (5, 'Biała Rawska'),
    (5, 'Sieradz'),
    (5, 'Błaszki'),
    (5, 'Warta'),
    (5, 'Złoczew'),
    (5, 'Tomaszów Mazowiecki'),
    (5, 'Wieluń'),
    (5, 'Wieruszów'),
    (5, 'Zduńska Wola'),
    (5, 'Szadek'),
    (5, 'Głowno'),
    (5, 'Ozorków'),
    (5, 'Zgierz'),
    (5, 'Aleksandrów Łódzki'),
    (5, 'Stryków'),
    (5, 'Brzeziny'),
    (5, 'Łódź'),
    (5, 'Piotrków Trybunalski'),
    (5, 'Skierniewice'),
    (6, 'Bochnia'),
    (6, 'Nowy Wiśnicz'),
    (6, 'Brzesko'),
    (6, 'Czchów'),
    (6, 'Alwernia'),
    (6, 'Chrzanów'),
    (6, 'Libiąż'),
    (6, 'Trzebinia'),
    (6, 'Dąbrowa Tarnowska'),
    (6, 'Szczucin'),
    (6, 'Gorlice'),
    (6, 'Biecz'),
    (6, 'Bobowa'),
    (6, 'Krzeszowice'),
    (6, 'Skała'),
    (6, 'Skawina'),
    (6, 'Słomniki'),
    (6, 'Świątniki Górne'),
    (6, 'Limanowa'),
    (6, 'Mszana Dolna'),
    (6, 'Miechów'),
    (6, 'Dobczyce'),
    (6, 'Myślenice'),
    (6, 'Sułkowice'),
    (6, 'Grybów'),
    (6, 'Krynica-Zdrój'),
    (6, 'Muszyna'),
    (6, 'Piwniczna-Zdrój'),
    (6, 'Stary Sącz'),
    (6, 'Nowy Targ'),
    (6, 'Szczawnica'),
    (6, 'Rabka-Zdrój'),
    (6, 'Bukowno'),
    (6, 'Olkusz'),
    (6, 'Wolbrom'),
    (6, 'Oświęcim'),
    (6, 'Brzeszcze'),
    (6, 'Chełmek'),
    (6, 'Kęty'),
    (6, 'Zator'),
    (6, 'Nowe Brzesko'),
    (6, 'Proszowice'),
    (6, 'Jordanów'),
    (6, 'Sucha Beskidzka'),
    (6, 'Maków Podhalański'),
    (6, 'Ciężkowice'),
    (6, 'Radłów'),
    (6, 'Ryglice'),
    (6, 'Tuchów'),
    (6, 'Wojnicz'),
    (6, 'Zakliczyn'),
    (6, 'Żabno'),
    (6, 'Zakopane'),
    (6, 'Andrychów'),
    (6, 'Kalwaria Zebrzydowska'),
    (6, 'Wadowice'),
    (6, 'Niepołomice'),
    (6, 'Wieliczka'),
    (6, 'Kraków'),
    (6, 'Nowy Sącz'),
    (6, 'Tarnów'),
    (7, 'Białobrzegi'),
    (7, 'Wyśmierzyce'),
    (7, 'Ciechanów'),
    (7, 'Glinojeck'),
    (7, 'Garwolin'),
    (7, 'Łaskarzew'),
    (7, 'Pilawa'),
    (7, 'Żelechów'),
    (7, 'Gostynin'),
    (7, 'Milanówek'),
    (7, 'Podkowa Leśna'),
    (7, 'Grodzisk Mazowiecki'),
    (7, 'Grójec'),
    (7, 'Mogielnica'),
    (7, 'Nowe Miasto nad Pilicą'),
    (7, 'Warka'),
    (7, 'Kozienice'),
    (7, 'Legionowo'),
    (7, 'Serock'),
    (7, 'Lipsko'),
    (7, 'Łosice'),
    (7, 'Maków Mazowiecki'),
    (7, 'Różan'),
    (7, 'Mińsk Mazowiecki'),
    (7, 'Halinów'),
    (7, 'Kałuszyn'),
    (7, 'Mrozy'),
    (7, 'Sulejówek'),
    (7, 'Mława'),
    (7, 'Nowy Dwór Mazowiecki'),
    (7, 'Nasielsk'),
    (7, 'Zakroczym'),
    (7, 'Myszyniec'),
    (7, 'Ostrów Mazowiecka'),
    (7, 'Brok'),
    (7, 'Józefów'),
    (7, 'Otwock'),
    (7, 'Karczew'),
    (7, 'Góra Kalwaria'),
    (7, 'Konstancin-Jeziorna'),
    (7, 'Piaseczno'),
    (7, 'Tarczyn'),
    (7, 'Drobin'),
    (7, 'Gąbin'),
    (7, 'Wyszogród'),
    (7, 'Płońsk'),
    (7, 'Raciąż'),
    (7, 'Piastów'),
    (7, 'Pruszków'),
    (7, 'Brwinów'),
    (7, 'Przasnysz'),
    (7, 'Chorzele'),
    (7, 'Przysucha'),
    (7, 'Pułtusk'),
    (7, 'Pionki'),
    (7, 'Iłża'),
    (7, 'Skaryszew'),
    (7, 'Mordy'),
    (7, 'Sierpc'),
    (7, 'Sochaczew'),
    (7, 'Sokołów Podlaski'),
    (7, 'Kosów Lacki'),
    (7, 'Szydłowiec'),
    (7, 'Błonie'),
    (7, 'Łomianki'),
    (7, 'Ożarów Mazowiecki'),
    (7, 'Węgrów'),
    (7, 'Łochów'),
    (7, 'Kobyłka'),
    (7, 'Marki'),
    (7, 'Ząbki'),
    (7, 'Zielonka'),
    (7, 'Radzymin'),
    (7, 'Tłuszcz'),
    (7, 'Wołomin'),
    (7, 'Wyszków'),
    (7, 'Zwoleń'),
    (7, 'Bieżuń'),
    (7, 'Żuromin'),
    (7, 'Żyrardów'),
    (7, 'Mszczonów'),
    (7, 'Ostrołęka'),
    (7, 'Płock'),
    (7, 'Radom'),
    (7, 'Siedlce'),
    (8, 'Brzeg'),
    (8, 'Grodków'),
    (8, 'Lewin Brzeski'),
    (8, 'Baborów'),
    (8, 'Głubczyce'),
    (8, 'Kietrz'),
    (8, 'Kędzierzyn-Koźle'),
    (8, 'Byczyna'),
    (8, 'Kluczbork'),
    (8, 'Wołczyn'),
    (8, 'Gogolin'),
    (8, 'Krapkowice'),
    (8, 'Zdzieszowice'),
    (8, 'Namysłów'),
    (8, 'Głuchołazy'),
    (8, 'Korfantów'),
    (8, 'Nysa'),
    (8, 'Otmuchów'),
    (8, 'Paczków'),
    (8, 'Dobrodzień'),
    (8, 'Gorzów Śląski'),
    (8, 'Olesno'),
    (8, 'Praszka'),
    (8, 'Niemodlin'),
    (8, 'Ozimek'),
    (8, 'Prószków'),
    (8, 'Biała'),
    (8, 'Głogówek'),
    (8, 'Prudnik'),
    (8, 'Kolonowskie'),
    (8, 'Leśnica'),
    (8, 'Strzelce Opolskie'),
    (8, 'Ujazd'),
    (8, 'Zawadzkie'),
    (8, 'Opole'),
    (9, 'Ustrzyki Dolne'),
    (9, 'Brzozów'),
    (9, 'Dębica'),
    (9, 'Brzostek'),
    (9, 'Pilzno'),
    (9, 'Jarosław'),
    (9, 'Radymno'),
    (9, 'Pruchnik'),
    (9, 'Jasło'),
    (9, 'Kołaczyce'),
    (9, 'Kolbuszowa'),
    (9, 'Dukla'),
    (9, 'Iwonicz-Zdrój'),
    (9, 'Jedlicze'),
    (9, 'Rymanów'),
    (9, 'Leżajsk'),
    (9, 'Nowa Sarzyna'),
    (9, 'Lubaczów'),
    (9, 'Cieszanów'),
    (9, 'Narol'),
    (9, 'Oleszyce'),
    (9, 'Łańcut'),
    (9, 'Mielec'),
    (9, 'Przecław'),
    (9, 'Radomyśl Wielki'),
    (9, 'Nisko'),
    (9, 'Rudnik nad Sanem'),
    (9, 'Ulanów'),
    (9, 'Przeworsk'),
    (9, 'Kańczuga'),
    (9, 'Sieniawa'),
    (9, 'Ropczyce'),
    (9, 'Sędziszów Małopolski'),
    (9, 'Dynów'),
    (9, 'Błażowa'),
    (9, 'Boguchwała'),
    (9, 'Głogów Małopolski'),
    (9, 'Sokołów Małopolski'),
    (9, 'Tyczyn'),
    (9, 'Sanok'),
    (9, 'Zagórz'),
    (9, 'Stalowa Wola'),
    (9, 'Zaklików'),
    (9, 'Strzyżów'),
    (9, 'Baranów Sandomierski'),
    (9, 'Nowa Dęba'),
    (9, 'Lesko'),
    (9, 'Krosno'),
    (9, 'Przemyśl'),
    (9, 'Rzeszów'),
    (9, 'Tarnobrzeg'),
    (10, 'Augustów'),
    (10, 'Lipsk'),
    (10, 'Choroszcz'),
    (10, 'Czarna Białostocka'),
    (10, 'Łapy'),
    (10, 'Michałowo'),
    (10, 'Supraśl'),
    (10, 'Suraż'),
    (10, 'Tykocin'),
    (10, 'Wasilków'),
    (10, 'Zabłudów'),
    (10, 'Bielsk Podlaski'),
    (10, 'Brańsk'),
    (10, 'Grajewo'),
    (10, 'Rajgród'),
    (10, 'Szczuczyn'),
    (10, 'Hajnówka'),
    (10, 'Kleszczele'),
    (10, 'Kolno'),
    (10, 'Stawiski'),
    (10, 'Jedwabne'),
    (10, 'Nowogród'),
    (10, 'Goniądz'),
    (10, 'Knyszyn'),
    (10, 'Mońki'),
    (10, 'Sejny'),
    (10, 'Siemiatycze'),
    (10, 'Drohiczyn'),
    (10, 'Dąbrowa Białostocka'),
    (10, 'Krynki'),
    (10, 'Sokółka'),
    (10, 'Suchowola'),
    (10, 'Wysokie Mazowieckie'),
    (10, 'Ciechanowiec'),
    (10, 'Czyżew'),
    (10, 'Szepietowo'),
    (10, 'Zambrów'),
    (10, 'Białystok'),
    (10, 'Łomża'),
    (10, 'Suwałki'),
    (11, 'Bytów'),
    (11, 'Miastko'),
    (11, 'Chojnice'),
    (11, 'Brusy'),
    (11, 'Czersk'),
    (11, 'Człuchów'),
    (11, 'Czarne'),
    (11, 'Debrzno'),
    (11, 'Pruszcz Gdański'),
    (11, 'Kartuzy'),
    (11, 'Żukowo'),
    (11, 'Kościerzyna'),
    (11, 'Kwidzyn'),
    (11, 'Prabuty'),
    (11, 'Lębork'),
    (11, 'Łeba'),
    (11, 'Malbork'),
    (11, 'Nowy Staw'),
    (11, 'Krynica Morska'),
    (11, 'Nowy Dwór Gdański'),
    (11, 'Hel'),
    (11, 'Jastarnia'),
    (11, 'Puck'),
    (11, 'Władysławowo'),
    (11, 'Ustka'),
    (11, 'Kępice'),
    (11, 'Czarna Woda'),
    (11, 'Skórcz'),
    (11, 'Starogard Gdański'),
    (11, 'Skarszewy'),
    (11, 'Tczew'),
    (11, 'Gniew'),
    (11, 'Pelplin'),
    (11, 'Reda'),
    (11, 'Rumia'),
    (11, 'Wejherowo'),
    (11, 'Dzierzgoń'),
    (11, 'Sztum'),
    (11, 'Gdańsk'),
    (11, 'Gdynia'),
    (11, 'Słupsk'),
    (11, 'Sopot'),
    (12, 'Będzin'),
    (12, 'Czeladź'),
    (12, 'Wojkowice'),
    (12, 'Siewierz'),
    (12, 'Sławków'),
    (12, 'Szczyrk'),
    (12, 'Czechowice-Dziedzice'),
    (12, 'Wilamowice'),
    (12, 'Cieszyn'),
    (12, 'Ustroń'),
    (12, 'Wisła'),
    (12, 'Skoczów'),
    (12, 'Strumień'),
    (12, 'Blachownia'),
    (12, 'Koniecpol'),
    (12, 'Knurów'),
    (12, 'Pyskowice'),
    (12, 'Sośnicowice'),
    (12, 'Toszek'),
    (12, 'Kłobuck'),
    (12, 'Krzepice'),
    (12, 'Lubliniec'),
    (12, 'Woźniki'),
    (12, 'Łaziska Górne'),
    (12, 'Mikołów'),
    (12, 'Orzesze'),
    (12, 'Myszków'),
    (12, 'Koziegłowy'),
    (12, 'Żarki'),
    (12, 'Pszczyna'),
    (12, 'Racibórz'),
    (12, 'Krzanowice'),
    (12, 'Kuźnia Raciborska'),
    (12, 'Czerwionka-Leszczyny'),
    (12, 'Kalety'),
    (12, 'Miasteczko Śląskie'),
    (12, 'Radzionków'),
    (12, 'Tarnowskie Góry'),
    (12, 'Bieruń'),
    (12, 'Imielin'),
    (12, 'Lędziny'),
    (12, 'Pszów'),
    (12, 'Radlin'),
    (12, 'Rydułtowy'),
    (12, 'Wodzisław Śląski'),
    (12, 'Poręba'),
    (12, 'Zawiercie'),
    (12, 'Łazy'),
    (12, 'Ogrodzieniec'),
    (12, 'Pilica'),
    (12, 'Szczekociny'),
    (12, 'Żywiec'),
    (12, 'Bielsko-Biała'),
    (12, 'Bytom'),
    (12, 'Chorzów'),
    (12, 'Częstochowa'),
    (12, 'Dąbrowa Górnicza'),
    (12, 'Gliwice'),
    (12, 'Jastrzębie-Zdrój'),
    (12, 'Jaworzno'),
    (12, 'Katowice'),
    (12, 'Mysłowice'),
    (12, 'Piekary Śląskie'),
    (12, 'Ruda Śląska'),
    (12, 'Rybnik'),
    (12, 'Siemianowice Śląskie'),
    (12, 'Sosnowiec'),
    (12, 'Świętochłowice'),
    (12, 'Tychy'),
    (12, 'Zabrze'),
    (12, 'Żory'),
    (13, 'Busko-Zdrój'),
    (13, 'Stopnica'),
    (13, 'Jędrzejów'),
    (13, 'Małogoszcz'),
    (13, 'Sędziszów'),
    (13, 'Kazimierza Wielka'),
    (13, 'Skalbmierz'),
    (13, 'Bodzentyn'),
    (13, 'Chęciny'),
    (13, 'Chmielnik'),
    (13, 'Daleszyce'),
    (13, 'Końskie'),
    (13, 'Stąporków'),
    (13, 'Opatów'),
    (13, 'Ożarów'),
    (13, 'Ostrowiec Świętokrzyski'),
    (13, 'Ćmielów'),
    (13, 'Kunów'),
    (13, 'Działoszyce'),
    (13, 'Pińczów'),
    (13, 'Sandomierz'),
    (13, 'Koprzywnica'),
    (13, 'Zawichost'),
    (13, 'Skarżysko-Kamienna'),
    (13, 'Suchedniów'),
    (13, 'Starachowice'),
    (13, 'Wąchock'),
    (13, 'Osiek'),
    (13, 'Połaniec'),
    (13, 'Staszów'),
    (13, 'Włoszczowa'),
    (13, 'Kielce'),
    (14, 'Bartoszyce'),
    (14, 'Górowo Iławeckie'),
    (14, 'Bisztynek'),
    (14, 'Sępopol'),
    (14, 'Braniewo'),
    (14, 'Frombork'),
    (14, 'Pieniężno'),
    (14, 'Działdowo'),
    (14, 'Lidzbark'),
    (14, 'Młynary'),
    (14, 'Pasłęk'),
    (14, 'Tolkmicko'),
    (14, 'Ełk'),
    (14, 'Giżycko'),
    (14, 'Ryn'),
    (14, 'Iława'),
    (14, 'Lubawa'),
    (14, 'Kisielice'),
    (14, 'Susz'),
    (14, 'Zalewo'),
    (14, 'Kętrzyn'),
    (14, 'Korsze'),
    (14, 'Reszel'),
    (14, 'Lidzbark Warmiński'),
    (14, 'Orneta'),
    (14, 'Mrągowo'),
    (14, 'Mikołajki'),
    (14, 'Nidzica'),
    (14, 'Nowe Miasto Lubawskie'),
    (14, 'Olecko'),
    (14, 'Barczewo'),
    (14, 'Biskupiec'),
    (14, 'Dobre Miasto'),
    (14, 'Jeziorany'),
    (14, 'Olsztynek'),
    (14, 'Ostróda'),
    (14, 'Miłakowo'),
    (14, 'Miłomłyn'),
    (14, 'Morąg'),
    (14, 'Biała Piska'),
    (14, 'Orzysz'),
    (14, 'Pisz'),
    (14, 'Ruciane-Nida'),
    (14, 'Szczytno'),
    (14, 'Pasym'),
    (14, 'Gołdap'),
    (14, 'Węgorzewo'),
    (14, 'Elbląg'),
    (14, 'Olsztyn'),
    (15, 'Chodzież'),
    (15, 'Margonin'),
    (15, 'Szamocin'),
    (15, 'Czarnków'),
    (15, 'Krzyż Wielkopolski'),
    (15, 'Trzcianka'),
    (15, 'Wieleń'),
    (15, 'Gniezno'),
    (15, 'Czerniejewo'),
    (15, 'Kłecko'),
    (15, 'Trzemeszno'),
    (15, 'Witkowo'),
    (15, 'Borek Wielkopolski'),
    (15, 'Gostyń'),
    (15, 'Krobia'),
    (15, 'Pogorzela'),
    (15, 'Poniec'),
    (15, 'Grodzisk Wielkopolski'),
    (15, 'Rakoniewice'),
    (15, 'Wielichowo'),
    (15, 'Jaraczewo'),
    (15, 'Jarocin'),
    (15, 'Żerków'),
    (15, 'Stawiszyn'),
    (15, 'Kępno'),
    (15, 'Koło'),
    (15, 'Dąbie'),
    (15, 'Kłodawa'),
    (15, 'Przedecz'),
    (15, 'Golina'),
    (15, 'Kleczew'),
    (15, 'Rychwał'),
    (15, 'Sompolno'),
    (15, 'Ślesin'),
    (15, 'Kościan'),
    (15, 'Czempiń'),
    (15, 'Krzywiń'),
    (15, 'Śmigiel'),
    (15, 'Sulmierzyce'),
    (15, 'Kobylin'),
    (15, 'Koźmin Wielkopolski'),
    (15, 'Krotoszyn'),
    (15, 'Zduny'),
    (15, 'Osieczna'),
    (15, 'Rydzyna'),
    (15, 'Międzychód'),
    (15, 'Sieraków'),
    (15, 'Lwówek'),
    (15, 'Nowy Tomyśl'),
    (15, 'Opalenica'),
    (15, 'Zbąszyń'),
    (15, 'Oborniki'),
    (15, 'Rogoźno'),
    (15, 'Ostrów Wielkopolski'),
    (15, 'Nowe Skalmierzyce'),
    (15, 'Odolanów'),
    (15, 'Raszków'),
    (15, 'Grabów nad Prosną'),
    (15, 'Mikstat'),
    (15, 'Ostrzeszów'),
    (15, 'Piła'),
    (15, 'Łobżenica'),
    (15, 'Ujście'),
    (15, 'Wyrzysk'),
    (15, 'Wysoka'),
    (15, 'Chocz'),
    (15, 'Dobrzyca'),
    (15, 'Pleszew'),
    (15, 'Luboń'),
    (15, 'Puszczykowo'),
    (15, 'Buk'),
    (15, 'Kostrzyn'),
    (15, 'Kórnik'),
    (15, 'Mosina'),
    (15, 'Murowana Goślina'),
    (15, 'Pobiedziska'),
    (15, 'Stęszew'),
    (15, 'Swarzędz'),
    (15, 'Bojanowo'),
    (15, 'Jutrosin'),
    (15, 'Miejska Górka'),
    (15, 'Rawicz'),
    (15, 'Słupca'),
    (15, 'Zagórów'),
    (15, 'Obrzycko'),
    (15, 'Ostroróg'),
    (15, 'Pniewy'),
    (15, 'Szamotuły'),
    (15, 'Wronki'),
    (15, 'Środa Wielkopolska'),
    (15, 'Dolsk'),
    (15, 'Książ Wielkopolski'),
    (15, 'Śrem'),
    (15, 'Turek'),
    (15, 'Dobra'),
    (15, 'Tuliszków'),
    (15, 'Wągrowiec'),
    (15, 'Gołańcz'),
    (15, 'Skoki'),
    (15, 'Wolsztyn'),
    (15, 'Miłosław'),
    (15, 'Nekla'),
    (15, 'Pyzdry'),
    (15, 'Września'),
    (15, 'Złotów'),
    (15, 'Jastrowie'),
    (15, 'Krajenka'),
    (15, 'Okonek'),
    (15, 'Kalisz'),
    (15, 'Konin'),
    (15, 'Leszno'),
    (15, 'Poznań'),
    (16, 'Białogard'),
    (16, 'Karlino'),
    (16, 'Tychowo'),
    (16, 'Choszczno'),
    (16, 'Drawno'),
    (16, 'Pełczyce'),
    (16, 'Recz'),
    (16, 'Czaplinek'),
    (16, 'Drawsko Pomorskie'),
    (16, 'Kalisz Pomorski'),
    (16, 'Złocieniec'),
    (16, 'Goleniów'),
    (16, 'Maszewo'),
    (16, 'Nowogard'),
    (16, 'Stepnica'),
    (16, 'Gryfice'),
    (16, 'Płoty'),
    (16, 'Trzebiatów'),
    (16, 'Cedynia'),
    (16, 'Chojna'),
    (16, 'Gryfino'),
    (16, 'Mieszkowice'),
    (16, 'Moryń'),
    (16, 'Trzcińsko-Zdrój'),
    (16, 'Dziwnów'),
    (16, 'Golczewo'),
    (16, 'Kamień Pomorski'),
    (16, 'Międzyzdroje'),
    (16, 'Wolin'),
    (16, 'Kołobrzeg'),
    (16, 'Gościno'),
    (16, 'Bobolice'),
    (16, 'Polanów'),
    (16, 'Sianów'),
    (16, 'Barlinek'),
    (16, 'Dębno'),
    (16, 'Myślibórz'),
    (16, 'Nowe Warpno'),
    (16, 'Police'),
    (16, 'Lipiany'),
    (16, 'Pyrzyce'),
    (16, 'Darłowo'),
    (16, 'Sławno'),
    (16, 'Stargard'),
    (16, 'Chociwel'),
    (16, 'Dobrzany'),
    (16, 'Ińsko'),
    (16, 'Suchań'),
    (16, 'Szczecinek'),
    (16, 'Barwice'),
    (16, 'Biały Bór'),
    (16, 'Borne Sulinowo'),
    (16, 'Świdwin'),
    (16, 'Połczyn-Zdrój'),
    (16, 'Wałcz'),
    (16, 'Człopa'),
    (16, 'Mirosławiec'),
    (16, 'Tuczno'),
    (16, 'Dobra'),
    (16, 'Łobez'),
    (16, 'Resko'),
    (16, 'Węgorzyno'),
    (16, 'Koszalin'),
    (16, 'Szczecin'),
    (16, 'Świnoujście');
/*!40000 ALTER TABLE `miasta` ENABLE KEYS */;

-- Zrzut struktury tabela pogoda.woje
CREATE TABLE IF NOT EXISTS city_states (
    id serial PRIMARY KEY,
    name varchar(50) DEFAULT NULL
);

INSERT INTO city_states (name) VALUES
    ('DOLNOŚLĄSKIE'),
    ('KUJAWSKO-POMORSKIE'),
    ('LUBELSKIE'),
    ('LUBUSKIE'),
    ('ŁÓDZKIE'),
    ('MAŁOPOLSKIE'),
    ('MAZOWIECKIE'),
    ('OPOLSKIE'),
    ('PODKARPACKIE'),
    ('PODLASKIE'),
    ('POMORSKIE'),
    ('ŚLĄSKIE'),
    ('ŚWIĘTOKRZYSKIE'),
    ('WARMIŃSKO-MAZURSKIE'),
    ('WIELKOPOLSKIE'),
    ('ZACHODNIOPOMORSKIE');
-- /*!40000 ALTER TABLE `woje` ENABLE KEYS */;
--
-- /*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
-- /*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
-- /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
